command:
  - "gunicorn"
  - "-w"
  - "1"
  - "-k"
  - "sync"
  - "-t"
  - "120"
  - "dash_app:server"
env:
  - name: "LAKEBASE_DB_NAME"
    value: "adtech-series-db-do-not-delete"
  - name: "POSTGRES_GROUP"
    value: "Adtech Series DB Access Role"
  - name: "AGENT_ENDPOINT"
    value: "chat_history_agent_postgres_genie"
  - name: "AGENT_CHAT_K"
    value: "10"
  - name: "CHAT_CONTEXT_LIMIT"
    value: "0"
  - name: "CONTEXT_WINDOW_SIZE"
    value: "200000"
  - name: "CONTEXT_WARNING_THRESHOLD"
    value: "0.9"
  - name: "OBJC_DISABLE_INITIALIZE_FORK_SAFETY"
    value: "YES"
  - name: "DASHBOARD_IFRAME"
    value: "https://e2-demo-field-eng.cloud.databricks.com/embed/dashboardsv3/01f072fd333618bcab36a77b0bb921ab?o=1444828305810485"
