"""add_chat_sessions_table_and_relationships

Revision ID: 7bdda0f34a51
Revises: 928e160f25aa
Create Date: 2025-08-05 09:37:41.900639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bdda0f34a51'
down_revision: Union[str, None] = '928e160f25aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_updated', 'chat_sessions', ['user_name', 'updated_at'], unique=False)
    op.create_index(op.f('ix_chat_sessions_user_name'), 'chat_sessions', ['user_name'], unique=False)
    op.create_foreign_key(None, 'chat_history', 'chat_sessions', ['chat_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_history', type_='foreignkey')
    op.drop_index(op.f('ix_chat_sessions_user_name'), table_name='chat_sessions')
    op.drop_index('idx_user_updated', table_name='chat_sessions')
    op.drop_table('chat_sessions')
    # ### end Alembic commands ###
