"""Add adding chat history

Revision ID: 928e160f25aa
Revises: 7ed60a629ebf
Create Date: 2025-07-30 16:41:35.195343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '928e160f25aa'
down_revision: Union[str, None] = '7ed60a629ebf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.String(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=False),
    sa.Column('message_type', sa.Enum('USER', 'ASSISTANT', name='messagetype'), nullable=False),
    sa.Column('message_content', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('message_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_chat_user_order', 'chat_history', ['chat_id', 'user_name', 'message_order'], unique=False)
    op.create_index(op.f('ix_chat_history_chat_id'), 'chat_history', ['chat_id'], unique=False)
    op.create_index(op.f('ix_chat_history_user_name'), 'chat_history', ['user_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_history_user_name'), table_name='chat_history')
    op.drop_index(op.f('ix_chat_history_chat_id'), table_name='chat_history')
    op.drop_index('idx_chat_user_order', table_name='chat_history')
    op.drop_table('chat_history')
    op.execute('DROP TYPE IF EXISTS messagetype;')
    # ### end Alembic commands ###
